[package]
name = "aoc-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
env_logger = "0.11.8"
itertools = "0.14.0"
log = "0.4.28"
rayon = "1.11.0"
z3 = "0.19.5"
